//-------------------------------------------------------------------------------------------------
// *** f8c generated file: DO NOT EDIT! Created: 2017-07-21 10:33:35 ***
//-------------------------------------------------------------------------------------------------
/*

Fix8 is released under the GNU LESSER GENERAL PUBLIC LICENSE Version 3.

Fix8 Open Source FIX Engine.
Copyright (C) 2010-17 David L. Dight <fix@fix8.org>

Fix8 is free software: you can  redistribute it and / or modify  it under the  terms of the
GNU Lesser General  Public License as  published  by the Free  Software Foundation,  either
version 3 of the License, or (at your option) any later version.

Fix8 is distributed in the hope  that it will be useful, but WITHOUT ANY WARRANTY;  without
even the  implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

You should  have received a copy of the GNU Lesser General Public  License along with Fix8.
If not, see <http://www.gnu.org/licenses/>.

*******************************************************************************************
*                Special note for Fix8 compiler generated source code                     *
*                                                                                         *
* Binary works  that are the results of compilation of code that is generated by the Fix8 *
* compiler  can be released  without releasing your  source code as  long as your  binary *
* links dynamically  against an  unmodified version of the Fix8 library.  You are however *
* required to leave the copyright text in the generated code.                             *
*                                                                                         *
*******************************************************************************************

BECAUSE THE PROGRAM IS  LICENSED FREE OF  CHARGE, THERE IS NO  WARRANTY FOR THE PROGRAM, TO
THE EXTENT  PERMITTED  BY  APPLICABLE  LAW.  EXCEPT WHEN  OTHERWISE  STATED IN  WRITING THE
COPYRIGHT HOLDERS AND/OR OTHER PARTIES  PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY
KIND,  EITHER EXPRESSED   OR   IMPLIED,  INCLUDING,  BUT   NOT  LIMITED   TO,  THE  IMPLIED
WARRANTIES  OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.  THE ENTIRE RISK AS TO
THE QUALITY AND PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE DEFECTIVE,
YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.

IN NO EVENT UNLESS REQUIRED  BY APPLICABLE LAW  OR AGREED TO IN  WRITING WILL ANY COPYRIGHT
HOLDER, OR  ANY OTHER PARTY  WHO MAY MODIFY  AND/OR REDISTRIBUTE  THE PROGRAM AS  PERMITTED
ABOVE,  BE  LIABLE  TO  YOU  FOR  DAMAGES,  INCLUDING  ANY  GENERAL, SPECIAL, INCIDENTAL OR
CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PROGRAM (INCLUDING BUT
NOT LIMITED TO LOSS OF DATA OR DATA BEING RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR
THIRD PARTIES OR A FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF SUCH
HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

*/

//-------------------------------------------------------------------------------------------------
#include <fix8/f8config.h>
#if defined FIX8_MAGIC_NUM && FIX8_MAGIC_NUM > 16789508L
#error CLIENT_types.cpp version 1.3.4 is out of date. Please regenerate with f8c.
#endif
//-------------------------------------------------------------------------------------------------
// CLIENT_types.cpp
//-------------------------------------------------------------------------------------------------
#include <iostream>
#include <fstream>
#include <iomanip>
#include <sstream>
#include <vector>
#include <map>
#include <list>
#include <set>
#include <iterator>
#include <algorithm>
#include <cerrno>
#include <string.h>
// f8 includes
#include <fix8/f8exception.hpp>
#include <fix8/hypersleep.hpp>
#include <fix8/mpmc.hpp>
#include <fix8/thread.hpp>
#include <fix8/f8types.hpp>
#include <fix8/f8utils.hpp>
#include <fix8/tickval.hpp>
#include <fix8/logger.hpp>
#include <fix8/traits.hpp>
#include <fix8/field.hpp>
#include <fix8/message.hpp>
#include "CLIENT_types.hpp"
//-------------------------------------------------------------------------------------------------
namespace FIX8 {
namespace CLIENT {

namespace {

//-------------------------------------------------------------------------------------------------
const char AdvSide_realm[]  
   { 'B', 'S', 'T', 'X' };
const char *AdvSide_descriptions[]  
   { "BUY", "SELL", "TRADE", "CROSS" };
const f8String AdvTransType_realm[]  
   { "C", "N", "R" };
const char *AdvTransType_descriptions[]  
   { "CANCEL", "NEW", "REPLACE" };
const char CommType_realm[]  
   { '1', '2', '3' };
const char *CommType_descriptions[]  
   { "PER_SHARE", "PERCENTAGE", "ABSOLUTE" };
const f8String ExecInst_realm[]  
   { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "I", "L", "M", "N", "O", "P", "R", "S", "T", "U", "V", "W" };
const char *ExecInst_descriptions[]  
   { "STAY_ON_OFFERSIDE", "NOT_HELD", "WORK", "GO_ALONG", "OVER_THE_DAY", "HELD", "PARTICIPATE_DONT_INITIATE", "STRICT_SCALE", "TRY_TO_SCALE", "STAY_ON_BIDSIDE", "NO_CROSS", "OK_TO_CROSS", "CALL_FIRST", "PERCENT_OF_VOLUME", "DO_NOT_INCREASE", "DO_NOT_REDUCE", "ALL_OR_NONE", "INSTITUTIONS_ONLY", "LAST_PEG", "MID_PRICE_PEG", "NON_NEGOTIABLE", "OPENING_PEG", "MARKET_PEG", "PRIMARY_PEG", "SUSPEND", "FIXED_PEG_TO_LOCAL_BEST_BID_OR_OFFER_AT_TIME_OF_ORDER", "CUSTOMER_DISPLAY_INSTRUCTION", "NETTING", "PEG_TO_VWAP" };
const char ExecTransType_realm[]  
   { '0', '1', '2', '3' };
const char *ExecTransType_descriptions[]  
   { "NEW", "CANCEL", "CORRECT", "STATUS" };
const char HandlInst_realm[]  
   { '1', '2', '3' };
const char *HandlInst_descriptions[]  
   { "AUTOMATED_EXECUTION_ORDER_PRIVATE_NO_BROKER_INTERVENTION", "AUTOMATED_EXECUTION_ORDER_PUBLIC_BROKER_INTERVENTION_OK", "MANUAL_ORDER_BEST_EXECUTION" };
const f8String IDSource_realm[]  
   { "1", "2", "3", "4", "5", "6", "7", "8", "9" };
const char *IDSource_descriptions[]  
   { "CUSIP", "SEDOL", "QUIK", "ISIN_NUMBER", "RIC_CODE", "ISO_CURRENCY_CODE", "ISO_COUNTRY_CODE", "EXCHANGE_SYMBOL", "CONSOLIDATED_TAPE_ASSOCIATION" };
const char IOIQltyInd_realm[]  
   { 'H', 'L', 'M' };
const char *IOIQltyInd_descriptions[]  
   { "HIGH", "LOW", "MEDIUM" };
const f8String IOIShares_realm[]  
   { "L", "M", "S" };
const char *IOIShares_descriptions[]  
   { "LARGE", "MEDIUM", "SMALL" };
const char IOITransType_realm[]  
   { 'C', 'N', 'R' };
const char *IOITransType_descriptions[]  
   { "CANCEL", "NEW", "REPLACE" };
const char LastCapacity_realm[]  
   { '1', '2', '3', '4' };
const char *LastCapacity_descriptions[]  
   { "AGENT", "CROSS_AS_AGENT", "CROSS_AS_PRINCIPAL", "PRINCIPAL" };
const f8String MsgType_realm[]  
   { "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "A", "B", "C", "D", "E", "F", "G", "H", "J", "K", "L", "M", "N", "P", "Q", "R", "S", "T", "V", "W", "X", "Y", "Z", "a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m" };
const char *MsgType_descriptions[]  
   { "HEARTBEAT", "TEST_REQUEST", "RESEND_REQUEST", "REJECT", "SEQUENCE_RESET", "LOGOUT", "INDICATION_OF_INTEREST", "ADVERTISEMENT", "EXECUTION_REPORT", "ORDER_CANCEL_REJECT", "LOGON", "NEWS", "EMAIL", "ORDER_SINGLE", "ORDER_LIST", "ORDER_CANCEL_REQUEST", "ORDER_CANCEL_REPLACE_REQUEST", "ORDER_STATUS_REQUEST", "ALLOCATION", "LIST_CANCEL_REQUEST", "LIST_EXECUTE", "LIST_STATUS_REQUEST", "LIST_STATUS", "ALLOCATION_ACK", "DONT_KNOW_TRADE", "QUOTE_REQUEST", "QUOTE", "SETTLEMENT_INSTRUCTIONS", "MARKET_DATA_REQUEST", "MARKET_DATA_SNAPSHOT_FULL_REFRESH", "MARKET_DATA_INCREMENTAL_REFRESH", "MARKET_DATA_REQUEST_REJECT", "QUOTE_CANCEL", "QUOTE_STATUS_REQUEST", "QUOTE_ACKNOWLEDGEMENT", "SECURITY_DEFINITION_REQUEST", "SECURITY_DEFINITION", "SECURITY_STATUS_REQUEST", "SECURITY_STATUS", "TRADING_SESSION_STATUS_REQUEST", "TRADING_SESSION_STATUS", "MASS_QUOTE", "BUSINESS_MESSAGE_REJECT", "BID_REQUEST", "BID_RESPONSE", "LIST_STRIKE_PRICE" };
const char OrdStatus_realm[]  
   { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'U' };
const char *OrdStatus_descriptions[]  
   { "NEW", "PARTIALLY_FILLED", "FILLED", "DONE_FOR_DAY", "CANCELED", "REPLACED", "PENDING_CANCEL", "STOPPED", "REJECTED", "SUSPENDED", "PENDING_NEW", "CALCULATED", "EXPIRED", "ACCEPTED_FOR_BIDDING", "PENDING_REPLACE", "UNCHANGED" };
const char OrdType_realm[]  
   { '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'P' };
const char *OrdType_descriptions[]  
   { "MARKET", "LIMIT", "STOP", "STOP_LIMIT", "MARKET_ON_CLOSE", "WITH_OR_WITHOUT", "LIMIT_OR_BETTER", "LIMIT_WITH_OR_WITHOUT", "ON_BASIS", "ON_CLOSE", "LIMIT_ON_CLOSE", "FOREX_C", "PREVIOUSLY_QUOTED", "PREVIOUSLY_INDICATED", "FOREX_F", "FOREX_G", "FOREX_H", "FUNARI", "PEGGED" };
const char PossDupFlag_realm[]  
   { 'N', 'Y' };
const char *PossDupFlag_descriptions[]  
   { "NO", "YES" };
const char Rule80A_realm[]  
   { 'A', 'B', 'C', 'D', 'E', 'F', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'R', 'S', 'T', 'U', 'W', 'X', 'Y', 'Z' };
const char *Rule80A_descriptions[]  
   { "AGENCY_SINGLE_ORDER", "SHORT_EXEMPT_TRANSACTION_B", "PROGRAM_ORDER_NON_INDEX_ARB_FOR_MEMBER_FIRM_ORG", "PROGRAM_ORDER_INDEX_ARB_FOR_MEMBER_FIRM_ORG", "REGISTERED_EQUITY_MARKET_MAKER_TRADES", "SHORT_EXEMPT_TRANSACTION_F", "SHORT_EXEMPT_TRANSACTION_H", "INDIVIDUAL_INVESTOR_SINGLE_ORDER", "PROGRAM_ORDER_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER", "PROGRAM_ORDER_NON_INDEX_ARB_FOR_INDIVIDUAL_CUSTOMER", "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE", "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_MEMBER", "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_MEMBER", "COMPETING_DEALER_TRADES_O", "PRINCIPAL", "COMPETING_DEALER_TRADES_R", "SPECIALIST_TRADES", "COMPETING_DEALER_TRADES_T", "PROGRAM_ORDER_INDEX_ARB_FOR_OTHER_AGENCY", "ALL_OTHER_ORDERS_AS_AGENT_FOR_OTHER_MEMBER", "SHORT_EXEMPT_TRANSACTION_FOR_MEMBER_COMPETING_MARKET_MAKER_NOT_AFFILIATED_WITH_THE_FIRM_CLEARING_THE_TRADE", "PROGRAM_ORDER_NON_INDEX_ARB_FOR_OTHER_AGENCY", "SHORT_EXEMPT_TRANSACTION_FOR_NON_MEMBER_COMPETING_MARKET_MAKER" };
const char Side_realm[]  
   { '1', '2', '3', '4', '5', '6', '7', '8', '9' };
const char *Side_descriptions[]  
   { "BUY", "SELL", "BUY_MINUS", "SELL_PLUS", "SELL_SHORT", "SELL_SHORT_EXEMPT", "UNDISCLOSED", "CROSS", "CROSS_SHORT" };
const char TimeInForce_realm[]  
   { '0', '1', '2', '3', '4', '5', '6' };
const char *TimeInForce_descriptions[]  
   { "DAY", "GOOD_TILL_CANCEL", "AT_THE_OPENING", "IMMEDIATE_OR_CANCEL", "FILL_OR_KILL", "GOOD_TILL_CROSSING", "GOOD_TILL_DATE" };
const char Urgency_realm[]  
   { '0', '1', '2' };
const char *Urgency_descriptions[]  
   { "NORMAL", "FLASH", "BACKGROUND" };
const char SettlmntTyp_realm[]  
   { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' };
const char *SettlmntTyp_descriptions[]  
   { "REGULAR", "CASH", "NEXT_DAY", "T_PLUS_2", "T_PLUS_3", "T_PLUS_4", "FUTURE", "WHEN_ISSUED", "SELLERS_OPTION", "T_PLUS_5" };
const char AllocTransType_realm[]  
   { '0', '1', '2', '3', '4', '5' };
const char *AllocTransType_descriptions[]  
   { "NEW", "REPLACE", "CANCEL", "PRELIMINARY", "CALCULATED", "CALCULATED_WITHOUT_PRELIMINARY" };
const char OpenClose_realm[]  
   { 'C', 'O' };
const char *OpenClose_descriptions[]  
   { "CLOSE", "OPEN" };
const char ProcessCode_realm[]  
   { '0', '1', '2', '3', '4', '5', '6' };
const char *ProcessCode_descriptions[]  
   { "REGULAR", "SOFT_DOLLAR", "STEP_IN", "STEP_OUT", "SOFT_DOLLAR_STEP_IN", "SOFT_DOLLAR_STEP_OUT", "PLAN_SPONSOR" };
const int AllocStatus_realm[]  
   { 0, 1, 2, 3 };
const char *AllocStatus_descriptions[]  
   { "ACCEPTED", "REJECTED", "PARTIAL_ACCEPT", "RECEIVED" };
const int AllocRejCode_realm[]  
   { 0, 1, 2, 3, 4, 5, 6, 7 };
const char *AllocRejCode_descriptions[]  
   { "UNKNOWN_ACCOUNT", "INCORRECT_QUANTITY", "INCORRECT_AVERAGE_PRICE", "UNKNOWN_EXECUTING_BROKER_MNEMONIC", "COMMISSION_DIFFERENCE", "UNKNOWN_ORDERID", "UNKNOWN_LISTID", "OTHER" };
const char EmailType_realm[]  
   { '0', '1', '2' };
const char *EmailType_descriptions[]  
   { "NEW", "REPLY", "ADMIN_REPLY" };
const char PossResend_realm[]  
   { 'N', 'Y' };
const char *PossResend_descriptions[]  
   { "NO", "YES" };
const int EncryptMethod_realm[]  
   { 0, 1, 2, 3, 4, 5, 6 };
const char *EncryptMethod_descriptions[]  
   { "NONE", "PKCS", "DES", "PKCS_DES", "PGP_DES", "PGP_DES_MD5", "PEM_DES_MD5" };
const int CxlRejReason_realm[]  
   { 0, 1, 2, 3 };
const char *CxlRejReason_descriptions[]  
   { "TOO_LATE_TO_CANCEL", "UNKNOWN_ORDER", "BROKER_OPTION", "ORDER_ALREADY_IN_PENDING_CANCEL_OR_PENDING_REPLACE_STATUS" };
const int OrdRejReason_realm[]  
   { 0, 1, 2, 3, 4, 5, 6, 7, 8 };
const char *OrdRejReason_descriptions[]  
   { "BROKER_OPTION", "UNKNOWN_SYMBOL", "EXCHANGE_CLOSED", "ORDER_EXCEEDS_LIMIT", "TOO_LATE_TO_ENTER", "UNKNOWN_ORDER", "DUPLICATE_ORDER", "DUPLICATE_OF_A_VERBALLY_COMMUNICATED_ORDER", "STALE_ORDER" };
const char IOIQualifier_realm[]  
   { 'A', 'C', 'I', 'L', 'M', 'O', 'P', 'Q', 'R', 'S', 'T', 'V', 'W', 'X', 'Y', 'Z' };
const char *IOIQualifier_descriptions[]  
   { "ALL_OR_NONE", "AT_THE_CLOSE", "IN_TOUCH_WITH", "LIMIT", "MORE_BEHIND", "AT_THE_OPEN", "TAKING_A_POSITION", "AT_THE_MARKET", "READY_TO_TRADE", "PORTFOLIO_SHOW_N", "THROUGH_THE_DAY", "VERSUS", "INDICATION", "CROSSING_OPPORTUNITY", "AT_THE_MIDPOINT", "PRE_OPEN" };
const char ReportToExch_realm[]  
   { 'N', 'Y' };
const char *ReportToExch_descriptions[]  
   { "NO", "YES" };
const char LocateReqd_realm[]  
   { 'N', 'Y' };
const char *LocateReqd_descriptions[]  
   { "NO", "YES" };
const char ForexReq_realm[]  
   { 'N', 'Y' };
const char *ForexReq_descriptions[]  
   { "NO", "YES" };
const char GapFillFlag_realm[]  
   { 'N', 'Y' };
const char *GapFillFlag_descriptions[]  
   { "NO", "YES" };
const char DKReason_realm[]  
   { 'A', 'B', 'C', 'D', 'E', 'Z' };
const char *DKReason_descriptions[]  
   { "UNKNOWN_SYMBOL", "WRONG_SIDE", "QUANTITY_EXCEEDS_ORDER", "NO_MATCHING_ORDER", "PRICE_EXCEEDS_LIMIT", "OTHER" };
const char IOINaturalFlag_realm[]  
   { 'N', 'Y' };
const char *IOINaturalFlag_descriptions[]  
   { "NO", "YES" };
const char MiscFeeType_realm[]  
   { '1', '2', '3', '4', '5', '6', '7', '8', '9' };
const char *MiscFeeType_descriptions[]  
   { "REGULATORY", "TAX", "LOCAL_COMMISSION", "EXCHANGE_FEES", "STAMP", "LEVY", "OTHER", "MARKUP", "CONSUMPTION_TAX" };
const char ResetSeqNumFlag_realm[]  
   { 'N', 'Y' };
const char *ResetSeqNumFlag_descriptions[]  
   { "NO", "YES" };
const char ExecType_realm[]  
   { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'E', 'L' };
const char *ExecType_descriptions[]  
   { "NEW", "PARTIAL_FILL", "FILL", "DONE_FOR_DAY", "CANCELED", "REPLACE", "PENDING_CANCEL", "STOPPED", "REJECTED", "SUSPENDED", "PENDING_NEW", "CALCULATED", "EXPIRED", "RESTATED", "PENDING_REPLACE", "TRIGGERED_OR_ACTIVATED_BY_SYSTEM" };
const char SettlCurrFxRateCalc_realm[]  
   { 'D', 'M' };
const char *SettlCurrFxRateCalc_descriptions[]  
   { "DIVIDE", "MULTIPLY" };
const char SettlInstMode_realm[]  
   { '0', '1', '2', '3' };
const char *SettlInstMode_descriptions[]  
   { "DEFAULT", "STANDING_INSTRUCTIONS_PROVIDED", "SPECIFIC_ALLOCATION_ACCOUNT_OVERRIDING", "SPECIFIC_ALLOCATION_ACCOUNT_STANDING" };
const char SettlInstTransType_realm[]  
   { 'C', 'N', 'R' };
const char *SettlInstTransType_descriptions[]  
   { "CANCEL", "NEW", "REPLACE" };
const char SettlInstSource_realm[]  
   { '1', '2' };
const char *SettlInstSource_descriptions[]  
   { "BROKERS_INSTRUCTIONS", "INSTITUTIONS_INSTRUCTIONS" };
const f8String SettlLocation_realm[]  
   { "CED", "DTC", "EUR", "FED", "ISO Country Code", "PNY", "PTC" };
const char *SettlLocation_descriptions[]  
   { "CEDEL", "DEPOSITORY_TRUST_COMPANY", "EUROCLEAR", "FEDERAL_BOOK_ENTRY", "LOCAL_MARKET_SETTLE_LOCATION", "PHYSICAL", "PARTICIPANT_TRUST_COMPANY" };
const f8String SecurityType_realm[]  
   { "?", "BA", "CB", "CD", "CMO", "CORP", "CP", "CPP", "CS", "FHA", "FHL", "FN", "FOR", "FUT", "GN", "GOVT", "IET", "MF", "MIO", "MPO", "MPP", "MPT", "MUNI", "NONE", "OPT", "PS", "RP", "RVRP", "SL", "TD", "USTB", "WAR", "ZOO" };
const char *SecurityType_descriptions[]  
   { "WILDCARD_ENTRY", "BANKERS_ACCEPTANCE", "CONVERTIBLE_BOND", "CERTIFICATE_OF_DEPOSIT", "COLLATERALIZE_MORTGAGE_OBLIGATION", "CORPORATE_BOND", "COMMERCIAL_PAPER", "CORPORATE_PRIVATE_PLACEMENT", "COMMON_STOCK", "FEDERAL_HOUSING_AUTHORITY", "FEDERAL_HOME_LOAN", "FEDERAL_NATIONAL_MORTGAGE_ASSOCIATION", "FOREIGN_EXCHANGE_CONTRACT", "FUTURE", "GOVERNMENT_NATIONAL_MORTGAGE_ASSOCIATION", "TREASURIES_PLUS_AGENCY_DEBENTURE", "MORTGAGE_IOETTE", "MUTUAL_FUND", "MORTGAGE_INTEREST_ONLY", "MORTGAGE_PRINCIPAL_ONLY", "MORTGAGE_PRIVATE_PLACEMENT", "MISCELLANEOUS_PASS_THRU", "MUNICIPAL_BOND", "NO_ISITC_SECURITY_TYPE", "OPTION", "PREFERRED_STOCK", "REPURCHASE_AGREEMENT", "REVERSE_REPURCHASE_AGREEMENT", "STUDENT_LOAN_MARKETING_ASSOCIATION", "TIME_DEPOSIT", "US_TREASURY_BILL", "WARRANT", "CATS_TIGERS_LIONS" };
const int StandInstDbType_realm[]  
   { 0, 1, 2, 3 };
const char *StandInstDbType_descriptions[]  
   { "OTHER", "DTC_SID", "THOMSON_ALERT", "A_GLOBAL_CUSTODIAN" };
const int AllocLinkType_realm[]  
   { 0, 1 };
const char *AllocLinkType_descriptions[]  
   { "F_X_NETTING", "F_X_SWAP" };
const int PutOrCall_realm[]  
   { 0, 1 };
const char *PutOrCall_descriptions[]  
   { "PUT", "CALL" };
const int CoveredOrUncovered_realm[]  
   { 0, 1 };
const char *CoveredOrUncovered_descriptions[]  
   { "COVERED", "UNCOVERED" };
const int CustomerOrFirm_realm[]  
   { 0, 1 };
const char *CustomerOrFirm_descriptions[]  
   { "CUSTOMER", "FIRM" };
const char NotifyBrokerOfCredit_realm[]  
   { 'N', 'Y' };
const char *NotifyBrokerOfCredit_descriptions[]  
   { "NO", "YES" };
const int AllocHandlInst_realm[]  
   { 1, 2, 3 };
const char *AllocHandlInst_descriptions[]  
   { "MATCH", "FORWARD", "FORWARD_AND_MATCH" };
const int RoutingType_realm[]  
   { 1, 2, 3, 4 };
const char *RoutingType_descriptions[]  
   { "TARGET_FIRM", "TARGET_LIST", "BLOCK_FIRM", "BLOCK_LIST" };
const char Benchmark_realm[]  
   { '1', '2', '3', '4', '5', '6', '7', '8', '9' };
const char *Benchmark_descriptions[]  
   { "CURVE", "5_YR", "OLD_5", "10_YR", "OLD_10", "30_YR", "OLD_30", "3_MO_LIBOR", "6_MO_LIBOR" };
const char SubscriptionRequestType_realm[]  
   { '0', '1', '2' };
const char *SubscriptionRequestType_descriptions[]  
   { "SNAPSHOT", "SNAPSHOT_PLUS_UPDATES", "DISABLE_PREVIOUS_SNAPSHOT_PLUS_UPDATE_REQUEST" };
const int MDUpdateType_realm[]  
   { 0, 1 };
const char *MDUpdateType_descriptions[]  
   { "FULL_REFRESH", "INCREMENTAL_REFRESH" };
const char AggregatedBook_realm[]  
   { 'N', 'Y' };
const char *AggregatedBook_descriptions[]  
   { "NO", "YES" };
const char MDEntryType_realm[]  
   { '0', '1', '2', '3', '4', '5', '6', '7', '8', '9' };
const char *MDEntryType_descriptions[]  
   { "BID", "OFFER", "TRADE", "INDEX_VALUE", "OPENING_PRICE", "CLOSING_PRICE", "SETTLEMENT_PRICE", "TRADING_SESSION_HIGH_PRICE", "TRADING_SESSION_LOW_PRICE", "TRADING_SESSION_VWAP_PRICE" };
const char TickDirection_realm[]  
   { '0', '1', '2', '3' };
const char *TickDirection_descriptions[]  
   { "PLUS_TICK", "ZERO_PLUS_TICK", "MINUS_TICK", "ZERO_MINUS_TICK" };
const f8String QuoteCondition_realm[]  
   { "A", "B", "C", "D", "E", "F", "G", "H", "I" };
const char *QuoteCondition_descriptions[]  
   { "OPEN", "CLOSED", "EXCHANGE_BEST", "CONSOLIDATED_BEST", "LOCKED", "CROSSED", "DEPTH", "FAST_TRADING", "NON_FIRM" };
const f8String TradeCondition_realm[]  
   { "A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N" };
const char *TradeCondition_descriptions[]  
   { "CASH", "AVERAGE_PRICE_TRADE", "CASH_TRADE", "NEXT_DAY", "OPENING", "INTRADAY_TRADE_DETAIL", "RULE_127_TRADE", "RULE_155_TRADE", "SOLD_LAST", "NEXT_DAY_TRADE", "OPENED", "SELLER", "SOLD", "STOPPED_STOCK" };
const char MDUpdateAction_realm[]  
   { '0', '1', '2' };
const char *MDUpdateAction_descriptions[]  
   { "NEW", "CHANGE", "DELETE" };
const char MDReqRejReason_realm[]  
   { '0', '1', '2', '3', '4', '5', '6', '7', '8' };
const char *MDReqRejReason_descriptions[]  
   { "UNKNOWN_SYMBOL", "DUPLICATE_MDREQID", "INSUFFICIENT_BANDWIDTH", "INSUFFICIENT_PERMISSIONS", "UNSUPPORTED_SUBSCRIPTIONREQUESTTYPE", "UNSUPPORTED_MARKETDEPTH", "UNSUPPORTED_MDUPDATETYPE", "UNSUPPORTED_AGGREGATEDBOOK", "UNSUPPORTED_MDENTRYTYPE" };
const char DeleteReason_realm[]  
   { '0', '1' };
const char *DeleteReason_descriptions[]  
   { "CANCELATION", "ERROR" };
const char OpenCloseSettleFlag_realm[]  
   { '0', '1', '2' };
const char *OpenCloseSettleFlag_descriptions[]  
   { "DAILY_OPEN", "SESSION_OPEN", "DELIVERY_SETTLEMENT_PRICE" };
const char FinancialStatus_realm[]  
   { '1' };
const char *FinancialStatus_descriptions[]  
   { "BANKRUPT" };
const char CorporateAction_realm[]  
   { 'A', 'B', 'C', 'D', 'E' };
const char *CorporateAction_descriptions[]  
   { "EX_DIVIDEND", "EX_DISTRIBUTION", "EX_RIGHTS", "NEW", "EX_INTEREST" };
const int QuoteAckStatus_realm[]  
   { 0, 1, 2, 3, 4, 5 };
const char *QuoteAckStatus_descriptions[]  
   { "ACCEPTED", "CANCELED_FOR_SYMBOL", "CANCELED_FOR_SECURITY_TYPE", "CANCELED_FOR_UNDERLYING", "CANCELED_ALL", "REJECTED" };
const int QuoteCancelType_realm[]  
   { 1, 2, 3, 4 };
const char *QuoteCancelType_descriptions[]  
   { "CANCEL_FOR_SYMBOL", "CANCEL_FOR_SECURITY_TYPE", "CANCEL_FOR_UNDERLYING_SYMBOL", "CANCEL_FOR_ALL_QUOTES" };
const int QuoteRejectReason_realm[]  
   { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
const char *QuoteRejectReason_descriptions[]  
   { "UNKNOWN_SYMBOL", "EXCHANGE", "QUOTE_REQUEST_EXCEEDS_LIMIT", "TOO_LATE_TO_ENTER", "UNKNOWN_QUOTE", "DUPLICATE_QUOTE", "INVALID_BID_ASK_SPREAD", "INVALID_PRICE", "NOT_AUTHORIZED_TO_QUOTE_SECURITY" };
const int QuoteResponseLevel_realm[]  
   { 0, 1, 2 };
const char *QuoteResponseLevel_descriptions[]  
   { "NO_ACKNOWLEDGEMENT", "ACKNOWLEDGE_ONLY_NEGATIVE_OR_ERRONEOUS_QUOTES", "ACKNOWLEDGE_EACH_QUOTE_MESSAGES" };
const int QuoteRequestType_realm[]  
   { 1, 2 };
const char *QuoteRequestType_descriptions[]  
   { "MANUAL", "AUTOMATIC" };
const int SecurityRequestType_realm[]  
   { 0, 1, 2, 3 };
const char *SecurityRequestType_descriptions[]  
   { "REQUEST_SECURITY_IDENTITY_AND_SPECIFICATIONS", "REQUEST_SECURITY_IDENTITY_FOR_THE_SPECIFICATIONS_PROVIDED", "REQUEST_LIST_SECURITY_TYPES", "REQUEST_LIST_SECURITIES" };
const int SecurityResponseType_realm[]  
   { 1, 2, 3, 4, 5, 6 };
const char *SecurityResponseType_descriptions[]  
   { "ACCEPT_SECURITY_PROPOSAL_AS_IS", "ACCEPT_SECURITY_PROPOSAL_WITH_REVISIONS_AS_INDICATED_IN_THE_MESSAGE", "LIST_OF_SECURITY_TYPES_RETURNED_PER_REQUEST", "LIST_OF_SECURITIES_RETURNED_PER_REQUEST", "REJECT_SECURITY_PROPOSAL", "CAN_NOT_MATCH_SELECTION_CRITERIA" };
const char UnsolicitedIndicator_realm[]  
   { 'N', 'Y' };
const char *UnsolicitedIndicator_descriptions[]  
   { "NO", "YES" };
const int SecurityTradingStatus_realm[]  
   { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20 };
const char *SecurityTradingStatus_descriptions[]  
   { "OPENING_DELAY", "TRADING_HALT", "RESUME", "NO_OPEN_NO_RESUME", "PRICE_INDICATION", "TRADING_RANGE_INDICATION", "MARKET_IMBALANCE_BUY", "MARKET_IMBALANCE_SELL", "MARKET_ON_CLOSE_IMBALANCE_BUY", "MARKET_ON_CLOSE_IMBALANCE_SELL", "11", "NO_MARKET_IMBALANCE", "NO_MARKET_ON_CLOSE_IMBALANCE", "ITS_PRE_OPENING", "NEW_PRICE_INDICATION", "TRADE_DISSEMINATION_TIME", "READY_TO_TRADE", "NOT_AVAILABLE_FOR_TRADING", "NOT_TRADED_ON_THIS_MARKET", "UNKNOWN_OR_INVALID" };
const char HaltReasonChar_realm[]  
   { 'D', 'E', 'I', 'M', 'P', 'X' };
const char *HaltReasonChar_descriptions[]  
   { "NEWS_DISSEMINATION", "ORDER_INFLUX", "ORDER_IMBALANCE", "ADDITIONAL_INFORMATION", "NEWS_PENDING", "EQUIPMENT_CHANGEOVER" };
const char InViewOfCommon_realm[]  
   { 'N', 'Y' };
const char *InViewOfCommon_descriptions[]  
   { "NO", "YES" };
const char DueToRelated_realm[]  
   { 'N', 'Y' };
const char *DueToRelated_descriptions[]  
   { "NO", "YES" };
const int Adjustment_realm[]  
   { 1, 2, 3 };
const char *Adjustment_descriptions[]  
   { "CANCEL", "ERROR", "CORRECTION" };
const int TradSesMethod_realm[]  
   { 1, 2, 3 };
const char *TradSesMethod_descriptions[]  
   { "ELECTRONIC", "OPEN_OUTCRY", "TWO_PARTY" };
const int TradSesMode_realm[]  
   { 1, 2, 3 };
const char *TradSesMode_descriptions[]  
   { "TESTING", "SIMULATED", "PRODUCTION" };
const int TradSesStatus_realm[]  
   { 1, 2, 3, 4, 5 };
const char *TradSesStatus_descriptions[]  
   { "HALTED", "OPEN", "CLOSED", "PRE_OPEN", "PRE_CLOSE" };
const f8String MessageEncoding_realm[]  
   { "EUC-JP", "ISO-2022-JP", "SHIFT_JIS", "UTF-8" };
const char *MessageEncoding_descriptions[]  
   { "EUC_JP", "ISO_2022_JP", "SHIFT_JIS", "UTF_8" };
const int QuoteEntryRejectReason_realm[]  
   { 1, 2, 3, 4, 5, 6, 7, 8, 9 };
const char *QuoteEntryRejectReason_descriptions[]  
   { "UNKNOWN_SYMBOL", "EXCHANGE", "QUOTE_EXCEEDS_LIMIT", "TOO_LATE_TO_ENTER", "UNKNOWN_QUOTE", "DUPLICATE_QUOTE", "INVALID_BID_ASK_SPREAD", "INVALID_PRICE", "NOT_AUTHORIZED_TO_QUOTE_SECURITY" };
const int SessionRejectReason_realm[]  
   { 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11 };
const char *SessionRejectReason_descriptions[]  
   { "INVALID_TAG_NUMBER", "REQUIRED_TAG_MISSING", "TAG_NOT_DEFINED_FOR_THIS_MESSAGE_TYPE", "UNDEFINED_TAG", "TAG_SPECIFIED_WITHOUT_A_VALUE", "VALUE_IS_INCORRECT", "INCORRECT_DATA_FORMAT_FOR_VALUE", "DECRYPTION_PROBLEM", "SIGNATURE_PROBLEM", "COMPID_PROBLEM", "SENDINGTIME_ACCURACY_PROBLEM", "INVALID_MSGTYPE" };
const char BidRequestTransType_realm[]  
   { 'C', 'N' };
const char *BidRequestTransType_descriptions[]  
   { "CANCEL", "NO" };
const char SolicitedFlag_realm[]  
   { 'N', 'Y' };
const char *SolicitedFlag_descriptions[]  
   { "NO", "YES" };
const int ExecRestatementReason_realm[]  
   { 0, 1, 2, 3, 4, 5 };
const char *ExecRestatementReason_descriptions[]  
   { "GT_CORPORATE_ACTION", "GT_RENEWAL", "VERBAL_CHANGE", "REPRICING_OF_ORDER", "BROKER_OPTION", "PARTIAL_DECLINE_OF_ORDERQTY" };
const int BusinessRejectReason_realm[]  
   { 0, 1, 2, 3, 4, 5 };
const char *BusinessRejectReason_descriptions[]  
   { "OTHER", "UNKOWN_ID", "UNKNOWN_SECURITY", "UNSUPPORTED_MESSAGE_TYPE", "APPLICATION_NOT_AVAILABLE", "CONDITIONALLY_REQUIRED_FIELD_MISSING" };
const char MsgDirection_realm[]  
   { 'R', 'S' };
const char *MsgDirection_descriptions[]  
   { "RECEIVE", "SEND" };
const char DiscretionInst_realm[]  
   { '0', '1', '2', '3', '4', '5' };
const char *DiscretionInst_descriptions[]  
   { "RELATED_TO_DISPLAYED_PRICE", "RELATED_TO_MARKET_PRICE", "RELATED_TO_PRIMARY_PRICE", "RELATED_TO_LOCAL_PRIMARY_PRICE", "RELATED_TO_MIDPOINT_PRICE", "RELATED_TO_LAST_TRADE_PRICE" };
const int LiquidityIndType_realm[]  
   { 1, 2, 3, 4 };
const char *LiquidityIndType_descriptions[]  
   { "5_DAY_MOVING_AVERAGE", "20_DAY_MOVING_AVERAGE", "NORMAL_MARKET_SIZE", "OTHER" };
const char ExchangeForPhysical_realm[]  
   { 'N', 'Y' };
const char *ExchangeForPhysical_descriptions[]  
   { "NO", "YES" };
const int ProgRptReqs_realm[]  
   { 1, 2, 3 };
const char *ProgRptReqs_descriptions[]  
   { "BUYSIDE_EXPLICITLY_REQUESTS_STATUS_USING_STATUSREQUEST", "SELLSIDE_PERIODICALLY_SENDS_STATUS_USING_LISTSTATUS_PERIOD_OPTIONALLY_SPECIFIED_IN_PROGRESSPERIOD", "REAL_TIME_EXECUTION_REPORTS" };
const int IncTaxInd_realm[]  
   { 1, 2 };
const char *IncTaxInd_descriptions[]  
   { "NET", "GROSS" };
const char TradeType_realm[]  
   { 'A', 'G', 'J', 'R' };
const char *TradeType_descriptions[]  
   { "AGENCY", "VWAP_GUARANTEE", "GUARANTEED_CLOSE", "RISK_TRADE" };
const char BasisPxType_realm[]  
   { '2', '3', '4', '5', '6', '7', '8', '9', 'A', 'B', 'C', 'D', 'Z' };
const char *BasisPxType_descriptions[]  
   { "CLOSING_PRICE_AT_MORNING_SESSION", "CLOSING_PRICE", "CURRENT_PRICE", "SQ", "VWAP_THROUGH_A_DAY", "VWAP_THROUGH_A_MORNING_SESSION", "VWAP_THROUGH_AN_AFTERNOON_SESSION", "VWAP_THROUGH_A_DAY_EXCEPT_YORI", "VWAP_THROUGH_A_MORNING_SESSION_EXCEPT_YORI", "VWAP_THROUGH_AN_AFTERNOON_SESSION_EXCEPT_YORI", "STRIKE", "OPEN", "OTHERS" };
const int PriceType_realm[]  
   { 1, 2, 3 };
const char *PriceType_descriptions[]  
   { "PERCENTAGE", "PER_SHARE", "FIXED_AMOUNT" };
const int GTBookingInst_realm[]  
   { 0, 1, 2 };
const char *GTBookingInst_descriptions[]  
   { "BOOK_OUT_ALL_TRADES_ON_DAY_OF_EXECUTION", "ACCUMULATE_EXECUTIONS_UNTIL_ORDER_IS_FILLED_OR_EXPIRES", "ACCUMULATE_UNTIL_VERBALLY_NOTIFIED_OTHERWISE" };
const int NetGrossInd_realm[]  
   { 1, 2 };
const char *NetGrossInd_descriptions[]  
   { "NET", "GROSS" };
const char ListExecInstType_realm[]  
   { '1', '2' };
const char *ListExecInstType_descriptions[]  
   { "IMMEDIATE", "WAIT_FOR_EXECUTE_INSTRUCTION" };
const char CxlRejResponseTo_realm[]  
   { '1', '2' };
const char *CxlRejResponseTo_descriptions[]  
   { "ORDER_CANCEL_REQUEST", "ORDER_CANCEL_REPLACE_REQUEST" };
const char MultiLegReportingType_realm[]  
   { '1', '2', '3' };
const char *MultiLegReportingType_descriptions[]  
   { "SINGLE_SECURITY", "INDIVIDUAL_LEG_OF_A_MULTI_LEG_SECURITY", "MULTI_LEG_SECURITY" };

//-------------------------------------------------------------------------------------------------
const RealmBase realmbases[] 
{
   { reinterpret_cast<const void *>(AdvSide_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, AdvSide_descriptions },
   { reinterpret_cast<const void *>(AdvTransType_realm), RealmBase::dt_set, FieldTrait::ft_string, 3, AdvTransType_descriptions },
   { reinterpret_cast<const void *>(CommType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, CommType_descriptions },
   { reinterpret_cast<const void *>(ExecInst_realm), RealmBase::dt_set, FieldTrait::ft_MultipleStringValue, 29, ExecInst_descriptions },
   { reinterpret_cast<const void *>(ExecTransType_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, ExecTransType_descriptions },
   { reinterpret_cast<const void *>(HandlInst_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, HandlInst_descriptions },
   { reinterpret_cast<const void *>(IDSource_realm), RealmBase::dt_set, FieldTrait::ft_string, 9, IDSource_descriptions },
   { reinterpret_cast<const void *>(IOIQltyInd_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, IOIQltyInd_descriptions },
   { reinterpret_cast<const void *>(IOIShares_realm), RealmBase::dt_set, FieldTrait::ft_string, 3, IOIShares_descriptions },
   { reinterpret_cast<const void *>(IOITransType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, IOITransType_descriptions },
   { reinterpret_cast<const void *>(LastCapacity_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, LastCapacity_descriptions },
   { reinterpret_cast<const void *>(MsgType_realm), RealmBase::dt_set, FieldTrait::ft_string, 46, MsgType_descriptions },
   { reinterpret_cast<const void *>(OrdStatus_realm), RealmBase::dt_set, FieldTrait::ft_char, 16, OrdStatus_descriptions },
   { reinterpret_cast<const void *>(OrdType_realm), RealmBase::dt_set, FieldTrait::ft_char, 19, OrdType_descriptions },
   { reinterpret_cast<const void *>(PossDupFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, PossDupFlag_descriptions },
   { reinterpret_cast<const void *>(Rule80A_realm), RealmBase::dt_set, FieldTrait::ft_char, 23, Rule80A_descriptions },
   { reinterpret_cast<const void *>(Side_realm), RealmBase::dt_set, FieldTrait::ft_char, 9, Side_descriptions },
   { reinterpret_cast<const void *>(TimeInForce_realm), RealmBase::dt_set, FieldTrait::ft_char, 7, TimeInForce_descriptions },
   { reinterpret_cast<const void *>(Urgency_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, Urgency_descriptions },
   { reinterpret_cast<const void *>(SettlmntTyp_realm), RealmBase::dt_set, FieldTrait::ft_char, 10, SettlmntTyp_descriptions },
   { reinterpret_cast<const void *>(AllocTransType_realm), RealmBase::dt_set, FieldTrait::ft_char, 6, AllocTransType_descriptions },
   { reinterpret_cast<const void *>(OpenClose_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, OpenClose_descriptions },
   { reinterpret_cast<const void *>(ProcessCode_realm), RealmBase::dt_set, FieldTrait::ft_char, 7, ProcessCode_descriptions },
   { reinterpret_cast<const void *>(AllocStatus_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, AllocStatus_descriptions },
   { reinterpret_cast<const void *>(AllocRejCode_realm), RealmBase::dt_set, FieldTrait::ft_int, 8, AllocRejCode_descriptions },
   { reinterpret_cast<const void *>(EmailType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, EmailType_descriptions },
   { reinterpret_cast<const void *>(PossResend_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, PossResend_descriptions },
   { reinterpret_cast<const void *>(EncryptMethod_realm), RealmBase::dt_set, FieldTrait::ft_int, 7, EncryptMethod_descriptions },
   { reinterpret_cast<const void *>(CxlRejReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, CxlRejReason_descriptions },
   { reinterpret_cast<const void *>(OrdRejReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 9, OrdRejReason_descriptions },
   { reinterpret_cast<const void *>(IOIQualifier_realm), RealmBase::dt_set, FieldTrait::ft_char, 16, IOIQualifier_descriptions },
   { reinterpret_cast<const void *>(ReportToExch_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ReportToExch_descriptions },
   { reinterpret_cast<const void *>(LocateReqd_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, LocateReqd_descriptions },
   { reinterpret_cast<const void *>(ForexReq_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ForexReq_descriptions },
   { reinterpret_cast<const void *>(GapFillFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, GapFillFlag_descriptions },
   { reinterpret_cast<const void *>(DKReason_realm), RealmBase::dt_set, FieldTrait::ft_char, 6, DKReason_descriptions },
   { reinterpret_cast<const void *>(IOINaturalFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, IOINaturalFlag_descriptions },
   { reinterpret_cast<const void *>(MiscFeeType_realm), RealmBase::dt_set, FieldTrait::ft_char, 9, MiscFeeType_descriptions },
   { reinterpret_cast<const void *>(ResetSeqNumFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ResetSeqNumFlag_descriptions },
   { reinterpret_cast<const void *>(ExecType_realm), RealmBase::dt_set, FieldTrait::ft_char, 16, ExecType_descriptions },
   { reinterpret_cast<const void *>(SettlCurrFxRateCalc_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, SettlCurrFxRateCalc_descriptions },
   { reinterpret_cast<const void *>(SettlInstMode_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, SettlInstMode_descriptions },
   { reinterpret_cast<const void *>(SettlInstTransType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, SettlInstTransType_descriptions },
   { reinterpret_cast<const void *>(SettlInstSource_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, SettlInstSource_descriptions },
   { reinterpret_cast<const void *>(SettlLocation_realm), RealmBase::dt_set, FieldTrait::ft_string, 7, SettlLocation_descriptions },
   { reinterpret_cast<const void *>(SecurityType_realm), RealmBase::dt_set, FieldTrait::ft_string, 33, SecurityType_descriptions },
   { reinterpret_cast<const void *>(StandInstDbType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, StandInstDbType_descriptions },
   { reinterpret_cast<const void *>(AllocLinkType_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, AllocLinkType_descriptions },
   { reinterpret_cast<const void *>(PutOrCall_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, PutOrCall_descriptions },
   { reinterpret_cast<const void *>(CoveredOrUncovered_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, CoveredOrUncovered_descriptions },
   { reinterpret_cast<const void *>(CustomerOrFirm_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, CustomerOrFirm_descriptions },
   { reinterpret_cast<const void *>(NotifyBrokerOfCredit_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, NotifyBrokerOfCredit_descriptions },
   { reinterpret_cast<const void *>(AllocHandlInst_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, AllocHandlInst_descriptions },
   { reinterpret_cast<const void *>(RoutingType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, RoutingType_descriptions },
   { reinterpret_cast<const void *>(Benchmark_realm), RealmBase::dt_set, FieldTrait::ft_char, 9, Benchmark_descriptions },
   { reinterpret_cast<const void *>(SubscriptionRequestType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, SubscriptionRequestType_descriptions },
   { reinterpret_cast<const void *>(MDUpdateType_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, MDUpdateType_descriptions },
   { reinterpret_cast<const void *>(AggregatedBook_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, AggregatedBook_descriptions },
   { reinterpret_cast<const void *>(MDEntryType_realm), RealmBase::dt_set, FieldTrait::ft_char, 10, MDEntryType_descriptions },
   { reinterpret_cast<const void *>(TickDirection_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, TickDirection_descriptions },
   { reinterpret_cast<const void *>(QuoteCondition_realm), RealmBase::dt_set, FieldTrait::ft_MultipleStringValue, 9, QuoteCondition_descriptions },
   { reinterpret_cast<const void *>(TradeCondition_realm), RealmBase::dt_set, FieldTrait::ft_MultipleStringValue, 14, TradeCondition_descriptions },
   { reinterpret_cast<const void *>(MDUpdateAction_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, MDUpdateAction_descriptions },
   { reinterpret_cast<const void *>(MDReqRejReason_realm), RealmBase::dt_set, FieldTrait::ft_char, 9, MDReqRejReason_descriptions },
   { reinterpret_cast<const void *>(DeleteReason_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, DeleteReason_descriptions },
   { reinterpret_cast<const void *>(OpenCloseSettleFlag_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, OpenCloseSettleFlag_descriptions },
   { reinterpret_cast<const void *>(FinancialStatus_realm), RealmBase::dt_set, FieldTrait::ft_char, 1, FinancialStatus_descriptions },
   { reinterpret_cast<const void *>(CorporateAction_realm), RealmBase::dt_set, FieldTrait::ft_char, 5, CorporateAction_descriptions },
   { reinterpret_cast<const void *>(QuoteAckStatus_realm), RealmBase::dt_set, FieldTrait::ft_int, 6, QuoteAckStatus_descriptions },
   { reinterpret_cast<const void *>(QuoteCancelType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, QuoteCancelType_descriptions },
   { reinterpret_cast<const void *>(QuoteRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 9, QuoteRejectReason_descriptions },
   { reinterpret_cast<const void *>(QuoteResponseLevel_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, QuoteResponseLevel_descriptions },
   { reinterpret_cast<const void *>(QuoteRequestType_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, QuoteRequestType_descriptions },
   { reinterpret_cast<const void *>(SecurityRequestType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, SecurityRequestType_descriptions },
   { reinterpret_cast<const void *>(SecurityResponseType_realm), RealmBase::dt_set, FieldTrait::ft_int, 6, SecurityResponseType_descriptions },
   { reinterpret_cast<const void *>(UnsolicitedIndicator_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, UnsolicitedIndicator_descriptions },
   { reinterpret_cast<const void *>(SecurityTradingStatus_realm), RealmBase::dt_set, FieldTrait::ft_int, 20, SecurityTradingStatus_descriptions },
   { reinterpret_cast<const void *>(HaltReasonChar_realm), RealmBase::dt_set, FieldTrait::ft_char, 6, HaltReasonChar_descriptions },
   { reinterpret_cast<const void *>(InViewOfCommon_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, InViewOfCommon_descriptions },
   { reinterpret_cast<const void *>(DueToRelated_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, DueToRelated_descriptions },
   { reinterpret_cast<const void *>(Adjustment_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, Adjustment_descriptions },
   { reinterpret_cast<const void *>(TradSesMethod_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, TradSesMethod_descriptions },
   { reinterpret_cast<const void *>(TradSesMode_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, TradSesMode_descriptions },
   { reinterpret_cast<const void *>(TradSesStatus_realm), RealmBase::dt_set, FieldTrait::ft_int, 5, TradSesStatus_descriptions },
   { reinterpret_cast<const void *>(MessageEncoding_realm), RealmBase::dt_set, FieldTrait::ft_string, 4, MessageEncoding_descriptions },
   { reinterpret_cast<const void *>(QuoteEntryRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 9, QuoteEntryRejectReason_descriptions },
   { reinterpret_cast<const void *>(SessionRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 12, SessionRejectReason_descriptions },
   { reinterpret_cast<const void *>(BidRequestTransType_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, BidRequestTransType_descriptions },
   { reinterpret_cast<const void *>(SolicitedFlag_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, SolicitedFlag_descriptions },
   { reinterpret_cast<const void *>(ExecRestatementReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 6, ExecRestatementReason_descriptions },
   { reinterpret_cast<const void *>(BusinessRejectReason_realm), RealmBase::dt_set, FieldTrait::ft_int, 6, BusinessRejectReason_descriptions },
   { reinterpret_cast<const void *>(MsgDirection_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, MsgDirection_descriptions },
   { reinterpret_cast<const void *>(DiscretionInst_realm), RealmBase::dt_set, FieldTrait::ft_char, 6, DiscretionInst_descriptions },
   { reinterpret_cast<const void *>(LiquidityIndType_realm), RealmBase::dt_set, FieldTrait::ft_int, 4, LiquidityIndType_descriptions },
   { reinterpret_cast<const void *>(ExchangeForPhysical_realm), RealmBase::dt_set, FieldTrait::ft_Boolean, 2, ExchangeForPhysical_descriptions },
   { reinterpret_cast<const void *>(ProgRptReqs_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, ProgRptReqs_descriptions },
   { reinterpret_cast<const void *>(IncTaxInd_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, IncTaxInd_descriptions },
   { reinterpret_cast<const void *>(TradeType_realm), RealmBase::dt_set, FieldTrait::ft_char, 4, TradeType_descriptions },
   { reinterpret_cast<const void *>(BasisPxType_realm), RealmBase::dt_set, FieldTrait::ft_char, 13, BasisPxType_descriptions },
   { reinterpret_cast<const void *>(PriceType_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, PriceType_descriptions },
   { reinterpret_cast<const void *>(GTBookingInst_realm), RealmBase::dt_set, FieldTrait::ft_int, 3, GTBookingInst_descriptions },
   { reinterpret_cast<const void *>(NetGrossInd_realm), RealmBase::dt_set, FieldTrait::ft_int, 2, NetGrossInd_descriptions },
   { reinterpret_cast<const void *>(ListExecInstType_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, ListExecInstType_descriptions },
   { reinterpret_cast<const void *>(CxlRejResponseTo_realm), RealmBase::dt_set, FieldTrait::ft_char, 2, CxlRejResponseTo_descriptions },
   { reinterpret_cast<const void *>(MultiLegReportingType_realm), RealmBase::dt_set, FieldTrait::ft_char, 3, MultiLegReportingType_descriptions },
};

//-------------------------------------------------------------------------------------------------

} // namespace

//-------------------------------------------------------------------------------------------------
extern const CLIENT_BaseEntry::Pair fldpairs[];
const CLIENT_BaseEntry::Pair fldpairs[] 
{
   { 1, { Type2Type<CLIENT::Account>(), "Account", 1 } },
   { 2, { Type2Type<CLIENT::AdvId>(), "AdvId", 2 } },
   { 3, { Type2Type<CLIENT::AdvRefID>(), "AdvRefID", 3 } },
   { 4, { Type2Type<CLIENT::AdvSide, char>(), "AdvSide", 4, &CLIENT::realmbases[0] } },
   { 5, { Type2Type<CLIENT::AdvTransType, f8String>(), "AdvTransType", 5, &CLIENT::realmbases[1] } },
   { 6, { Type2Type<CLIENT::AvgPx>(), "AvgPx", 6 } },
   { 7, { Type2Type<CLIENT::BeginSeqNo>(), "BeginSeqNo", 7 } },
   { 8, { Type2Type<CLIENT::BeginString>(), "BeginString", 8 } },
   { 9, { Type2Type<CLIENT::BodyLength>(), "BodyLength", 9 } },
   { 10, { Type2Type<CLIENT::CheckSum>(), "CheckSum", 10 } },
   { 11, { Type2Type<CLIENT::ClOrdID>(), "ClOrdID", 11 } },
   { 12, { Type2Type<CLIENT::Commission>(), "Commission", 12 } },
   { 13, { Type2Type<CLIENT::CommType, char>(), "CommType", 13, &CLIENT::realmbases[2] } },
   { 14, { Type2Type<CLIENT::CumQty>(), "CumQty", 14 } },
   { 15, { Type2Type<CLIENT::Currency>(), "Currency", 15 } },
   { 16, { Type2Type<CLIENT::EndSeqNo>(), "EndSeqNo", 16 } },
   { 17, { Type2Type<CLIENT::ExecID>(), "ExecID", 17 } },
   { 18, { Type2Type<CLIENT::ExecInst, f8String>(), "ExecInst", 18, &CLIENT::realmbases[3] } },
   { 19, { Type2Type<CLIENT::ExecRefID>(), "ExecRefID", 19 } },
   { 20, { Type2Type<CLIENT::ExecTransType, char>(), "ExecTransType", 20, &CLIENT::realmbases[4] } },
   { 21, { Type2Type<CLIENT::HandlInst, char>(), "HandlInst", 21, &CLIENT::realmbases[5] } },
   { 22, { Type2Type<CLIENT::IDSource, f8String>(), "IDSource", 22, &CLIENT::realmbases[6] } },
   { 23, { Type2Type<CLIENT::IOIid>(), "IOIid", 23 } },
   { 25, { Type2Type<CLIENT::IOIQltyInd, char>(), "IOIQltyInd", 25, &CLIENT::realmbases[7] } },
   { 26, { Type2Type<CLIENT::IOIRefID>(), "IOIRefID", 26 } },
   { 27, { Type2Type<CLIENT::IOIShares, f8String>(), "IOIShares", 27, &CLIENT::realmbases[8] } },
   { 28, { Type2Type<CLIENT::IOITransType, char>(), "IOITransType", 28, &CLIENT::realmbases[9] } },
   { 29, { Type2Type<CLIENT::LastCapacity, char>(), "LastCapacity", 29, &CLIENT::realmbases[10] } },
   { 30, { Type2Type<CLIENT::LastMkt>(), "LastMkt", 30 } },
   { 31, { Type2Type<CLIENT::LastPx>(), "LastPx", 31 } },
   { 32, { Type2Type<CLIENT::LastShares>(), "LastShares", 32 } },
   { 33, { Type2Type<CLIENT::LinesOfText>(), "LinesOfText", 33 } },
   { 34, { Type2Type<CLIENT::MsgSeqNum>(), "MsgSeqNum", 34 } },
   { 35, { Type2Type<CLIENT::MsgType, f8String>(), "MsgType", 35, &CLIENT::realmbases[11] } },
   { 36, { Type2Type<CLIENT::NewSeqNo>(), "NewSeqNo", 36 } },
   { 37, { Type2Type<CLIENT::OrderID>(), "OrderID", 37 } },
   { 38, { Type2Type<CLIENT::OrderQty>(), "OrderQty", 38 } },
   { 39, { Type2Type<CLIENT::OrdStatus, char>(), "OrdStatus", 39, &CLIENT::realmbases[12] } },
   { 40, { Type2Type<CLIENT::OrdType, char>(), "OrdType", 40, &CLIENT::realmbases[13] } },
   { 41, { Type2Type<CLIENT::OrigClOrdID>(), "OrigClOrdID", 41 } },
   { 42, { Type2Type<CLIENT::OrigTime>(), "OrigTime", 42 } },
   { 43, { Type2Type<CLIENT::PossDupFlag, char>(), "PossDupFlag", 43, &CLIENT::realmbases[14] } },
   { 44, { Type2Type<CLIENT::Price>(), "Price", 44 } },
   { 45, { Type2Type<CLIENT::RefSeqNum>(), "RefSeqNum", 45 } },
   { 46, { Type2Type<CLIENT::RelatdSym>(), "RelatdSym", 46 } },
   { 47, { Type2Type<CLIENT::Rule80A, char>(), "Rule80A", 47, &CLIENT::realmbases[15] } },
   { 48, { Type2Type<CLIENT::SecurityID>(), "SecurityID", 48 } },
   { 49, { Type2Type<CLIENT::SenderCompID>(), "SenderCompID", 49 } },
   { 50, { Type2Type<CLIENT::SenderSubID>(), "SenderSubID", 50 } },
   { 52, { Type2Type<CLIENT::SendingTime>(), "SendingTime", 52 } },
   { 53, { Type2Type<CLIENT::Shares>(), "Shares", 53 } },
   { 54, { Type2Type<CLIENT::Side, char>(), "Side", 54, &CLIENT::realmbases[16] } },
   { 55, { Type2Type<CLIENT::Symbol>(), "Symbol", 55 } },
   { 56, { Type2Type<CLIENT::TargetCompID>(), "TargetCompID", 56 } },
   { 57, { Type2Type<CLIENT::TargetSubID>(), "TargetSubID", 57 } },
   { 58, { Type2Type<CLIENT::Text>(), "Text", 58 } },
   { 59, { Type2Type<CLIENT::TimeInForce, char>(), "TimeInForce", 59, &CLIENT::realmbases[17] } },
   { 60, { Type2Type<CLIENT::TransactTime>(), "TransactTime", 60 } },
   { 61, { Type2Type<CLIENT::Urgency, char>(), "Urgency", 61, &CLIENT::realmbases[18] } },
   { 62, { Type2Type<CLIENT::ValidUntilTime>(), "ValidUntilTime", 62 } },
   { 63, { Type2Type<CLIENT::SettlmntTyp, char>(), "SettlmntTyp", 63, &CLIENT::realmbases[19] } },
   { 64, { Type2Type<CLIENT::FutSettDate>(), "FutSettDate", 64 } },
   { 65, { Type2Type<CLIENT::SymbolSfx>(), "SymbolSfx", 65 } },
   { 66, { Type2Type<CLIENT::ListID>(), "ListID", 66 } },
   { 67, { Type2Type<CLIENT::ListSeqNo>(), "ListSeqNo", 67 } },
   { 68, { Type2Type<CLIENT::TotNoOrders>(), "TotNoOrders", 68 } },
   { 69, { Type2Type<CLIENT::ListExecInst>(), "ListExecInst", 69 } },
   { 70, { Type2Type<CLIENT::AllocID>(), "AllocID", 70 } },
   { 71, { Type2Type<CLIENT::AllocTransType, char>(), "AllocTransType", 71, &CLIENT::realmbases[20] } },
   { 72, { Type2Type<CLIENT::RefAllocID>(), "RefAllocID", 72 } },
   { 73, { Type2Type<CLIENT::NoOrders>(), "NoOrders", 73 } },
   { 74, { Type2Type<CLIENT::AvgPrxPrecision>(), "AvgPrxPrecision", 74 } },
   { 75, { Type2Type<CLIENT::TradeDate>(), "TradeDate", 75 } },
   { 76, { Type2Type<CLIENT::ExecBroker>(), "ExecBroker", 76 } },
   { 77, { Type2Type<CLIENT::OpenClose, char>(), "OpenClose", 77, &CLIENT::realmbases[21] } },
   { 78, { Type2Type<CLIENT::NoAllocs>(), "NoAllocs", 78 } },
   { 79, { Type2Type<CLIENT::AllocAccount>(), "AllocAccount", 79 } },
   { 80, { Type2Type<CLIENT::AllocShares>(), "AllocShares", 80 } },
   { 81, { Type2Type<CLIENT::ProcessCode, char>(), "ProcessCode", 81, &CLIENT::realmbases[22] } },
   { 82, { Type2Type<CLIENT::NoRpts>(), "NoRpts", 82 } },
   { 83, { Type2Type<CLIENT::RptSeq>(), "RptSeq", 83 } },
   { 84, { Type2Type<CLIENT::CxlQty>(), "CxlQty", 84 } },
   { 87, { Type2Type<CLIENT::AllocStatus, int>(), "AllocStatus", 87, &CLIENT::realmbases[23] } },
   { 88, { Type2Type<CLIENT::AllocRejCode, int>(), "AllocRejCode", 88, &CLIENT::realmbases[24] } },
   { 89, { Type2Type<CLIENT::Signature>(), "Signature", 89 } },
   { 90, { Type2Type<CLIENT::SecureDataLen>(), "SecureDataLen", 90 } },
   { 91, { Type2Type<CLIENT::SecureData>(), "SecureData", 91 } },
   { 92, { Type2Type<CLIENT::BrokerOfCredit>(), "BrokerOfCredit", 92 } },
   { 93, { Type2Type<CLIENT::SignatureLength>(), "SignatureLength", 93 } },
   { 94, { Type2Type<CLIENT::EmailType, char>(), "EmailType", 94, &CLIENT::realmbases[25] } },
   { 95, { Type2Type<CLIENT::RawDataLength>(), "RawDataLength", 95 } },
   { 96, { Type2Type<CLIENT::RawData>(), "RawData", 96 } },
   { 97, { Type2Type<CLIENT::PossResend, char>(), "PossResend", 97, &CLIENT::realmbases[26] } },
   { 98, { Type2Type<CLIENT::EncryptMethod, int>(), "EncryptMethod", 98, &CLIENT::realmbases[27] } },
   { 99, { Type2Type<CLIENT::StopPx>(), "StopPx", 99 } },
   { 100, { Type2Type<CLIENT::ExDestination>(), "ExDestination", 100 } },
   { 102, { Type2Type<CLIENT::CxlRejReason, int>(), "CxlRejReason", 102, &CLIENT::realmbases[28] } },
   { 103, { Type2Type<CLIENT::OrdRejReason, int>(), "OrdRejReason", 103, &CLIENT::realmbases[29] } },
   { 104, { Type2Type<CLIENT::IOIQualifier, char>(), "IOIQualifier", 104, &CLIENT::realmbases[30] } },
   { 105, { Type2Type<CLIENT::WaveNo>(), "WaveNo", 105 } },
   { 106, { Type2Type<CLIENT::Issuer>(), "Issuer", 106 } },
   { 107, { Type2Type<CLIENT::SecurityDesc>(), "SecurityDesc", 107 } },
   { 108, { Type2Type<CLIENT::HeartBtInt>(), "HeartBtInt", 108 } },
   { 109, { Type2Type<CLIENT::ClientID>(), "ClientID", 109 } },
   { 110, { Type2Type<CLIENT::MinQty>(), "MinQty", 110 } },
   { 111, { Type2Type<CLIENT::MaxFloor>(), "MaxFloor", 111 } },
   { 112, { Type2Type<CLIENT::TestReqID>(), "TestReqID", 112 } },
   { 113, { Type2Type<CLIENT::ReportToExch, char>(), "ReportToExch", 113, &CLIENT::realmbases[31] } },
   { 114, { Type2Type<CLIENT::LocateReqd, char>(), "LocateReqd", 114, &CLIENT::realmbases[32] } },
   { 115, { Type2Type<CLIENT::OnBehalfOfCompID>(), "OnBehalfOfCompID", 115 } },
   { 116, { Type2Type<CLIENT::OnBehalfOfSubID>(), "OnBehalfOfSubID", 116 } },
   { 117, { Type2Type<CLIENT::QuoteID>(), "QuoteID", 117 } },
   { 118, { Type2Type<CLIENT::NetMoney>(), "NetMoney", 118 } },
   { 119, { Type2Type<CLIENT::SettlCurrAmt>(), "SettlCurrAmt", 119 } },
   { 120, { Type2Type<CLIENT::SettlCurrency>(), "SettlCurrency", 120 } },
   { 121, { Type2Type<CLIENT::ForexReq, char>(), "ForexReq", 121, &CLIENT::realmbases[33] } },
   { 122, { Type2Type<CLIENT::OrigSendingTime>(), "OrigSendingTime", 122 } },
   { 123, { Type2Type<CLIENT::GapFillFlag, char>(), "GapFillFlag", 123, &CLIENT::realmbases[34] } },
   { 124, { Type2Type<CLIENT::NoExecs>(), "NoExecs", 124 } },
   { 126, { Type2Type<CLIENT::ExpireTime>(), "ExpireTime", 126 } },
   { 127, { Type2Type<CLIENT::DKReason, char>(), "DKReason", 127, &CLIENT::realmbases[35] } },
   { 128, { Type2Type<CLIENT::DeliverToCompID>(), "DeliverToCompID", 128 } },
   { 129, { Type2Type<CLIENT::DeliverToSubID>(), "DeliverToSubID", 129 } },
   { 130, { Type2Type<CLIENT::IOINaturalFlag, char>(), "IOINaturalFlag", 130, &CLIENT::realmbases[36] } },
   { 131, { Type2Type<CLIENT::QuoteReqID>(), "QuoteReqID", 131 } },
   { 132, { Type2Type<CLIENT::BidPx>(), "BidPx", 132 } },
   { 133, { Type2Type<CLIENT::OfferPx>(), "OfferPx", 133 } },
   { 134, { Type2Type<CLIENT::BidSize>(), "BidSize", 134 } },
   { 135, { Type2Type<CLIENT::OfferSize>(), "OfferSize", 135 } },
   { 136, { Type2Type<CLIENT::NoMiscFees>(), "NoMiscFees", 136 } },
   { 137, { Type2Type<CLIENT::MiscFeeAmt>(), "MiscFeeAmt", 137 } },
   { 138, { Type2Type<CLIENT::MiscFeeCurr>(), "MiscFeeCurr", 138 } },
   { 139, { Type2Type<CLIENT::MiscFeeType, char>(), "MiscFeeType", 139, &CLIENT::realmbases[37] } },
   { 140, { Type2Type<CLIENT::PrevClosePx>(), "PrevClosePx", 140 } },
   { 141, { Type2Type<CLIENT::ResetSeqNumFlag, char>(), "ResetSeqNumFlag", 141, &CLIENT::realmbases[38] } },
   { 142, { Type2Type<CLIENT::SenderLocationID>(), "SenderLocationID", 142 } },
   { 143, { Type2Type<CLIENT::TargetLocationID>(), "TargetLocationID", 143 } },
   { 144, { Type2Type<CLIENT::OnBehalfOfLocationID>(), "OnBehalfOfLocationID", 144 } },
   { 145, { Type2Type<CLIENT::DeliverToLocationID>(), "DeliverToLocationID", 145 } },
   { 146, { Type2Type<CLIENT::NoRelatedSym>(), "NoRelatedSym", 146 } },
   { 147, { Type2Type<CLIENT::Subject>(), "Subject", 147 } },
   { 148, { Type2Type<CLIENT::Headline>(), "Headline", 148 } },
   { 149, { Type2Type<CLIENT::URLLink>(), "URLLink", 149 } },
   { 150, { Type2Type<CLIENT::ExecType, char>(), "ExecType", 150, &CLIENT::realmbases[39] } },
   { 151, { Type2Type<CLIENT::LeavesQty>(), "LeavesQty", 151 } },
   { 152, { Type2Type<CLIENT::CashOrderQty>(), "CashOrderQty", 152 } },
   { 153, { Type2Type<CLIENT::AllocAvgPx>(), "AllocAvgPx", 153 } },
   { 154, { Type2Type<CLIENT::AllocNetMoney>(), "AllocNetMoney", 154 } },
   { 155, { Type2Type<CLIENT::SettlCurrFxRate>(), "SettlCurrFxRate", 155 } },
   { 156, { Type2Type<CLIENT::SettlCurrFxRateCalc, char>(), "SettlCurrFxRateCalc", 156, &CLIENT::realmbases[40] } },
   { 157, { Type2Type<CLIENT::NumDaysInterest>(), "NumDaysInterest", 157 } },
   { 158, { Type2Type<CLIENT::AccruedInterestRate>(), "AccruedInterestRate", 158 } },
   { 159, { Type2Type<CLIENT::AccruedInterestAmt>(), "AccruedInterestAmt", 159 } },
   { 160, { Type2Type<CLIENT::SettlInstMode, char>(), "SettlInstMode", 160, &CLIENT::realmbases[41] } },
   { 161, { Type2Type<CLIENT::AllocText>(), "AllocText", 161 } },
   { 162, { Type2Type<CLIENT::SettlInstID>(), "SettlInstID", 162 } },
   { 163, { Type2Type<CLIENT::SettlInstTransType, char>(), "SettlInstTransType", 163, &CLIENT::realmbases[42] } },
   { 164, { Type2Type<CLIENT::EmailThreadID>(), "EmailThreadID", 164 } },
   { 165, { Type2Type<CLIENT::SettlInstSource, char>(), "SettlInstSource", 165, &CLIENT::realmbases[43] } },
   { 166, { Type2Type<CLIENT::SettlLocation, f8String>(), "SettlLocation", 166, &CLIENT::realmbases[44] } },
   { 167, { Type2Type<CLIENT::SecurityType, f8String>(), "SecurityType", 167, &CLIENT::realmbases[45] } },
   { 168, { Type2Type<CLIENT::EffectiveTime>(), "EffectiveTime", 168 } },
   { 169, { Type2Type<CLIENT::StandInstDbType, int>(), "StandInstDbType", 169, &CLIENT::realmbases[46] } },
   { 170, { Type2Type<CLIENT::StandInstDbName>(), "StandInstDbName", 170 } },
   { 171, { Type2Type<CLIENT::StandInstDbID>(), "StandInstDbID", 171 } },
   { 172, { Type2Type<CLIENT::SettlDeliveryType>(), "SettlDeliveryType", 172 } },
   { 173, { Type2Type<CLIENT::SettlDepositoryCode>(), "SettlDepositoryCode", 173 } },
   { 174, { Type2Type<CLIENT::SettlBrkrCode>(), "SettlBrkrCode", 174 } },
   { 175, { Type2Type<CLIENT::SettlInstCode>(), "SettlInstCode", 175 } },
   { 176, { Type2Type<CLIENT::SecuritySettlAgentName>(), "SecuritySettlAgentName", 176 } },
   { 177, { Type2Type<CLIENT::SecuritySettlAgentCode>(), "SecuritySettlAgentCode", 177 } },
   { 178, { Type2Type<CLIENT::SecuritySettlAgentAcctNum>(), "SecuritySettlAgentAcctNum", 178 } },
   { 179, { Type2Type<CLIENT::SecuritySettlAgentAcctName>(), "SecuritySettlAgentAcctName", 179 } },
   { 180, { Type2Type<CLIENT::SecuritySettlAgentContactName>(), "SecuritySettlAgentContactName", 180 } },
   { 181, { Type2Type<CLIENT::SecuritySettlAgentContactPhone>(), "SecuritySettlAgentContactPhone", 181 } },
   { 182, { Type2Type<CLIENT::CashSettlAgentName>(), "CashSettlAgentName", 182 } },
   { 183, { Type2Type<CLIENT::CashSettlAgentCode>(), "CashSettlAgentCode", 183 } },
   { 184, { Type2Type<CLIENT::CashSettlAgentAcctNum>(), "CashSettlAgentAcctNum", 184 } },
   { 185, { Type2Type<CLIENT::CashSettlAgentAcctName>(), "CashSettlAgentAcctName", 185 } },
   { 186, { Type2Type<CLIENT::CashSettlAgentContactName>(), "CashSettlAgentContactName", 186 } },
   { 187, { Type2Type<CLIENT::CashSettlAgentContactPhone>(), "CashSettlAgentContactPhone", 187 } },
   { 188, { Type2Type<CLIENT::BidSpotRate>(), "BidSpotRate", 188 } },
   { 189, { Type2Type<CLIENT::BidForwardPoints>(), "BidForwardPoints", 189 } },
   { 190, { Type2Type<CLIENT::OfferSpotRate>(), "OfferSpotRate", 190 } },
   { 191, { Type2Type<CLIENT::OfferForwardPoints>(), "OfferForwardPoints", 191 } },
   { 192, { Type2Type<CLIENT::OrderQty2>(), "OrderQty2", 192 } },
   { 193, { Type2Type<CLIENT::FutSettDate2>(), "FutSettDate2", 193 } },
   { 194, { Type2Type<CLIENT::LastSpotRate>(), "LastSpotRate", 194 } },
   { 195, { Type2Type<CLIENT::LastForwardPoints>(), "LastForwardPoints", 195 } },
   { 196, { Type2Type<CLIENT::AllocLinkID>(), "AllocLinkID", 196 } },
   { 197, { Type2Type<CLIENT::AllocLinkType, int>(), "AllocLinkType", 197, &CLIENT::realmbases[47] } },
   { 198, { Type2Type<CLIENT::SecondaryOrderID>(), "SecondaryOrderID", 198 } },
   { 199, { Type2Type<CLIENT::NoIOIQualifiers>(), "NoIOIQualifiers", 199 } },
   { 200, { Type2Type<CLIENT::MaturityMonthYear>(), "MaturityMonthYear", 200 } },
   { 201, { Type2Type<CLIENT::PutOrCall, int>(), "PutOrCall", 201, &CLIENT::realmbases[48] } },
   { 202, { Type2Type<CLIENT::StrikePrice>(), "StrikePrice", 202 } },
   { 203, { Type2Type<CLIENT::CoveredOrUncovered, int>(), "CoveredOrUncovered", 203, &CLIENT::realmbases[49] } },
   { 204, { Type2Type<CLIENT::CustomerOrFirm, int>(), "CustomerOrFirm", 204, &CLIENT::realmbases[50] } },
   { 205, { Type2Type<CLIENT::MaturityDay>(), "MaturityDay", 205 } },
   { 206, { Type2Type<CLIENT::OptAttribute>(), "OptAttribute", 206 } },
   { 207, { Type2Type<CLIENT::SecurityExchange>(), "SecurityExchange", 207 } },
   { 208, { Type2Type<CLIENT::NotifyBrokerOfCredit, char>(), "NotifyBrokerOfCredit", 208, &CLIENT::realmbases[51] } },
   { 209, { Type2Type<CLIENT::AllocHandlInst, int>(), "AllocHandlInst", 209, &CLIENT::realmbases[52] } },
   { 210, { Type2Type<CLIENT::MaxShow>(), "MaxShow", 210 } },
   { 211, { Type2Type<CLIENT::PegDifference>(), "PegDifference", 211 } },
   { 212, { Type2Type<CLIENT::XmlDataLen>(), "XmlDataLen", 212 } },
   { 213, { Type2Type<CLIENT::XmlData>(), "XmlData", 213 } },
   { 214, { Type2Type<CLIENT::SettlInstRefID>(), "SettlInstRefID", 214 } },
   { 215, { Type2Type<CLIENT::NoRoutingIDs>(), "NoRoutingIDs", 215 } },
   { 216, { Type2Type<CLIENT::RoutingType, int>(), "RoutingType", 216, &CLIENT::realmbases[53] } },
   { 217, { Type2Type<CLIENT::RoutingID>(), "RoutingID", 217 } },
   { 218, { Type2Type<CLIENT::SpreadToBenchmark>(), "SpreadToBenchmark", 218 } },
   { 219, { Type2Type<CLIENT::Benchmark, char>(), "Benchmark", 219, &CLIENT::realmbases[54] } },
   { 223, { Type2Type<CLIENT::CouponRate>(), "CouponRate", 223 } },
   { 231, { Type2Type<CLIENT::ContractMultiplier>(), "ContractMultiplier", 231 } },
   { 262, { Type2Type<CLIENT::MDReqID>(), "MDReqID", 262 } },
   { 263, { Type2Type<CLIENT::SubscriptionRequestType, char>(), "SubscriptionRequestType", 263, &CLIENT::realmbases[55] } },
   { 264, { Type2Type<CLIENT::MarketDepth>(), "MarketDepth", 264 } },
   { 265, { Type2Type<CLIENT::MDUpdateType, int>(), "MDUpdateType", 265, &CLIENT::realmbases[56] } },
   { 266, { Type2Type<CLIENT::AggregatedBook, char>(), "AggregatedBook", 266, &CLIENT::realmbases[57] } },
   { 267, { Type2Type<CLIENT::NoMDEntryTypes>(), "NoMDEntryTypes", 267 } },
   { 268, { Type2Type<CLIENT::NoMDEntries>(), "NoMDEntries", 268 } },
   { 269, { Type2Type<CLIENT::MDEntryType, char>(), "MDEntryType", 269, &CLIENT::realmbases[58] } },
   { 270, { Type2Type<CLIENT::MDEntryPx>(), "MDEntryPx", 270 } },
   { 271, { Type2Type<CLIENT::MDEntrySize>(), "MDEntrySize", 271 } },
   { 272, { Type2Type<CLIENT::MDEntryDate>(), "MDEntryDate", 272 } },
   { 273, { Type2Type<CLIENT::MDEntryTime>(), "MDEntryTime", 273 } },
   { 274, { Type2Type<CLIENT::TickDirection, char>(), "TickDirection", 274, &CLIENT::realmbases[59] } },
   { 275, { Type2Type<CLIENT::MDMkt>(), "MDMkt", 275 } },
   { 276, { Type2Type<CLIENT::QuoteCondition, f8String>(), "QuoteCondition", 276, &CLIENT::realmbases[60] } },
   { 277, { Type2Type<CLIENT::TradeCondition, f8String>(), "TradeCondition", 277, &CLIENT::realmbases[61] } },
   { 278, { Type2Type<CLIENT::MDEntryID>(), "MDEntryID", 278 } },
   { 279, { Type2Type<CLIENT::MDUpdateAction, char>(), "MDUpdateAction", 279, &CLIENT::realmbases[62] } },
   { 280, { Type2Type<CLIENT::MDEntryRefID>(), "MDEntryRefID", 280 } },
   { 281, { Type2Type<CLIENT::MDReqRejReason, char>(), "MDReqRejReason", 281, &CLIENT::realmbases[63] } },
   { 282, { Type2Type<CLIENT::MDEntryOriginator>(), "MDEntryOriginator", 282 } },
   { 283, { Type2Type<CLIENT::LocationID>(), "LocationID", 283 } },
   { 284, { Type2Type<CLIENT::DeskID>(), "DeskID", 284 } },
   { 285, { Type2Type<CLIENT::DeleteReason, char>(), "DeleteReason", 285, &CLIENT::realmbases[64] } },
   { 286, { Type2Type<CLIENT::OpenCloseSettleFlag, char>(), "OpenCloseSettleFlag", 286, &CLIENT::realmbases[65] } },
   { 287, { Type2Type<CLIENT::SellerDays>(), "SellerDays", 287 } },
   { 288, { Type2Type<CLIENT::MDEntryBuyer>(), "MDEntryBuyer", 288 } },
   { 289, { Type2Type<CLIENT::MDEntrySeller>(), "MDEntrySeller", 289 } },
   { 290, { Type2Type<CLIENT::MDEntryPositionNo>(), "MDEntryPositionNo", 290 } },
   { 291, { Type2Type<CLIENT::FinancialStatus, char>(), "FinancialStatus", 291, &CLIENT::realmbases[66] } },
   { 292, { Type2Type<CLIENT::CorporateAction, char>(), "CorporateAction", 292, &CLIENT::realmbases[67] } },
   { 293, { Type2Type<CLIENT::DefBidSize>(), "DefBidSize", 293 } },
   { 294, { Type2Type<CLIENT::DefOfferSize>(), "DefOfferSize", 294 } },
   { 295, { Type2Type<CLIENT::NoQuoteEntries>(), "NoQuoteEntries", 295 } },
   { 296, { Type2Type<CLIENT::NoQuoteSets>(), "NoQuoteSets", 296 } },
   { 297, { Type2Type<CLIENT::QuoteAckStatus, int>(), "QuoteAckStatus", 297, &CLIENT::realmbases[68] } },
   { 298, { Type2Type<CLIENT::QuoteCancelType, int>(), "QuoteCancelType", 298, &CLIENT::realmbases[69] } },
   { 299, { Type2Type<CLIENT::QuoteEntryID>(), "QuoteEntryID", 299 } },
   { 300, { Type2Type<CLIENT::QuoteRejectReason, int>(), "QuoteRejectReason", 300, &CLIENT::realmbases[70] } },
   { 301, { Type2Type<CLIENT::QuoteResponseLevel, int>(), "QuoteResponseLevel", 301, &CLIENT::realmbases[71] } },
   { 302, { Type2Type<CLIENT::QuoteSetID>(), "QuoteSetID", 302 } },
   { 303, { Type2Type<CLIENT::QuoteRequestType, int>(), "QuoteRequestType", 303, &CLIENT::realmbases[72] } },
   { 304, { Type2Type<CLIENT::TotQuoteEntries>(), "TotQuoteEntries", 304 } },
   { 305, { Type2Type<CLIENT::UnderlyingIDSource>(), "UnderlyingIDSource", 305 } },
   { 306, { Type2Type<CLIENT::UnderlyingIssuer>(), "UnderlyingIssuer", 306 } },
   { 307, { Type2Type<CLIENT::UnderlyingSecurityDesc>(), "UnderlyingSecurityDesc", 307 } },
   { 308, { Type2Type<CLIENT::UnderlyingSecurityExchange>(), "UnderlyingSecurityExchange", 308 } },
   { 309, { Type2Type<CLIENT::UnderlyingSecurityID>(), "UnderlyingSecurityID", 309 } },
   { 310, { Type2Type<CLIENT::UnderlyingSecurityType>(), "UnderlyingSecurityType", 310 } },
   { 311, { Type2Type<CLIENT::UnderlyingSymbol>(), "UnderlyingSymbol", 311 } },
   { 312, { Type2Type<CLIENT::UnderlyingSymbolSfx>(), "UnderlyingSymbolSfx", 312 } },
   { 313, { Type2Type<CLIENT::UnderlyingMaturityMonthYear>(), "UnderlyingMaturityMonthYear", 313 } },
   { 314, { Type2Type<CLIENT::UnderlyingMaturityDay>(), "UnderlyingMaturityDay", 314 } },
   { 315, { Type2Type<CLIENT::UnderlyingPutOrCall>(), "UnderlyingPutOrCall", 315 } },
   { 316, { Type2Type<CLIENT::UnderlyingStrikePrice>(), "UnderlyingStrikePrice", 316 } },
   { 317, { Type2Type<CLIENT::UnderlyingOptAttribute>(), "UnderlyingOptAttribute", 317 } },
   { 318, { Type2Type<CLIENT::UnderlyingCurrency>(), "UnderlyingCurrency", 318 } },
   { 319, { Type2Type<CLIENT::RatioQty>(), "RatioQty", 319 } },
   { 320, { Type2Type<CLIENT::SecurityReqID>(), "SecurityReqID", 320 } },
   { 321, { Type2Type<CLIENT::SecurityRequestType, int>(), "SecurityRequestType", 321, &CLIENT::realmbases[73] } },
   { 322, { Type2Type<CLIENT::SecurityResponseID>(), "SecurityResponseID", 322 } },
   { 323, { Type2Type<CLIENT::SecurityResponseType, int>(), "SecurityResponseType", 323, &CLIENT::realmbases[74] } },
   { 324, { Type2Type<CLIENT::SecurityStatusReqID>(), "SecurityStatusReqID", 324 } },
   { 325, { Type2Type<CLIENT::UnsolicitedIndicator, char>(), "UnsolicitedIndicator", 325, &CLIENT::realmbases[75] } },
   { 326, { Type2Type<CLIENT::SecurityTradingStatus, int>(), "SecurityTradingStatus", 326, &CLIENT::realmbases[76] } },
   { 327, { Type2Type<CLIENT::HaltReasonChar, char>(), "HaltReasonChar", 327, &CLIENT::realmbases[77] } },
   { 328, { Type2Type<CLIENT::InViewOfCommon, char>(), "InViewOfCommon", 328, &CLIENT::realmbases[78] } },
   { 329, { Type2Type<CLIENT::DueToRelated, char>(), "DueToRelated", 329, &CLIENT::realmbases[79] } },
   { 330, { Type2Type<CLIENT::BuyVolume>(), "BuyVolume", 330 } },
   { 331, { Type2Type<CLIENT::SellVolume>(), "SellVolume", 331 } },
   { 332, { Type2Type<CLIENT::HighPx>(), "HighPx", 332 } },
   { 333, { Type2Type<CLIENT::LowPx>(), "LowPx", 333 } },
   { 334, { Type2Type<CLIENT::Adjustment, int>(), "Adjustment", 334, &CLIENT::realmbases[80] } },
   { 335, { Type2Type<CLIENT::TradSesReqID>(), "TradSesReqID", 335 } },
   { 336, { Type2Type<CLIENT::TradingSessionID>(), "TradingSessionID", 336 } },
   { 337, { Type2Type<CLIENT::ContraTrader>(), "ContraTrader", 337 } },
   { 338, { Type2Type<CLIENT::TradSesMethod, int>(), "TradSesMethod", 338, &CLIENT::realmbases[81] } },
   { 339, { Type2Type<CLIENT::TradSesMode, int>(), "TradSesMode", 339, &CLIENT::realmbases[82] } },
   { 340, { Type2Type<CLIENT::TradSesStatus, int>(), "TradSesStatus", 340, &CLIENT::realmbases[83] } },
   { 341, { Type2Type<CLIENT::TradSesStartTime>(), "TradSesStartTime", 341 } },
   { 342, { Type2Type<CLIENT::TradSesOpenTime>(), "TradSesOpenTime", 342 } },
   { 343, { Type2Type<CLIENT::TradSesPreCloseTime>(), "TradSesPreCloseTime", 343 } },
   { 344, { Type2Type<CLIENT::TradSesCloseTime>(), "TradSesCloseTime", 344 } },
   { 345, { Type2Type<CLIENT::TradSesEndTime>(), "TradSesEndTime", 345 } },
   { 346, { Type2Type<CLIENT::NumberOfOrders>(), "NumberOfOrders", 346 } },
   { 347, { Type2Type<CLIENT::MessageEncoding, f8String>(), "MessageEncoding", 347, &CLIENT::realmbases[84] } },
   { 348, { Type2Type<CLIENT::EncodedIssuerLen>(), "EncodedIssuerLen", 348 } },
   { 349, { Type2Type<CLIENT::EncodedIssuer>(), "EncodedIssuer", 349 } },
   { 350, { Type2Type<CLIENT::EncodedSecurityDescLen>(), "EncodedSecurityDescLen", 350 } },
   { 351, { Type2Type<CLIENT::EncodedSecurityDesc>(), "EncodedSecurityDesc", 351 } },
   { 352, { Type2Type<CLIENT::EncodedListExecInstLen>(), "EncodedListExecInstLen", 352 } },
   { 353, { Type2Type<CLIENT::EncodedListExecInst>(), "EncodedListExecInst", 353 } },
   { 354, { Type2Type<CLIENT::EncodedTextLen>(), "EncodedTextLen", 354 } },
   { 355, { Type2Type<CLIENT::EncodedText>(), "EncodedText", 355 } },
   { 356, { Type2Type<CLIENT::EncodedSubjectLen>(), "EncodedSubjectLen", 356 } },
   { 357, { Type2Type<CLIENT::EncodedSubject>(), "EncodedSubject", 357 } },
   { 358, { Type2Type<CLIENT::EncodedHeadlineLen>(), "EncodedHeadlineLen", 358 } },
   { 359, { Type2Type<CLIENT::EncodedHeadline>(), "EncodedHeadline", 359 } },
   { 360, { Type2Type<CLIENT::EncodedAllocTextLen>(), "EncodedAllocTextLen", 360 } },
   { 361, { Type2Type<CLIENT::EncodedAllocText>(), "EncodedAllocText", 361 } },
   { 362, { Type2Type<CLIENT::EncodedUnderlyingIssuerLen>(), "EncodedUnderlyingIssuerLen", 362 } },
   { 363, { Type2Type<CLIENT::EncodedUnderlyingIssuer>(), "EncodedUnderlyingIssuer", 363 } },
   { 364, { Type2Type<CLIENT::EncodedUnderlyingSecurityDescLen>(), "EncodedUnderlyingSecurityDescLen", 364 } },
   { 365, { Type2Type<CLIENT::EncodedUnderlyingSecurityDesc>(), "EncodedUnderlyingSecurityDesc", 365 } },
   { 366, { Type2Type<CLIENT::AllocPrice>(), "AllocPrice", 366 } },
   { 367, { Type2Type<CLIENT::QuoteSetValidUntilTime>(), "QuoteSetValidUntilTime", 367 } },
   { 368, { Type2Type<CLIENT::QuoteEntryRejectReason, int>(), "QuoteEntryRejectReason", 368, &CLIENT::realmbases[85] } },
   { 369, { Type2Type<CLIENT::LastMsgSeqNumProcessed>(), "LastMsgSeqNumProcessed", 369 } },
   { 370, { Type2Type<CLIENT::OnBehalfOfSendingTime>(), "OnBehalfOfSendingTime", 370 } },
   { 371, { Type2Type<CLIENT::RefTagID>(), "RefTagID", 371 } },
   { 372, { Type2Type<CLIENT::RefMsgType>(), "RefMsgType", 372 } },
   { 373, { Type2Type<CLIENT::SessionRejectReason, int>(), "SessionRejectReason", 373, &CLIENT::realmbases[86] } },
   { 374, { Type2Type<CLIENT::BidRequestTransType, char>(), "BidRequestTransType", 374, &CLIENT::realmbases[87] } },
   { 375, { Type2Type<CLIENT::ContraBroker>(), "ContraBroker", 375 } },
   { 376, { Type2Type<CLIENT::ComplianceID>(), "ComplianceID", 376 } },
   { 377, { Type2Type<CLIENT::SolicitedFlag, char>(), "SolicitedFlag", 377, &CLIENT::realmbases[88] } },
   { 378, { Type2Type<CLIENT::ExecRestatementReason, int>(), "ExecRestatementReason", 378, &CLIENT::realmbases[89] } },
   { 379, { Type2Type<CLIENT::BusinessRejectRefID>(), "BusinessRejectRefID", 379 } },
   { 380, { Type2Type<CLIENT::BusinessRejectReason, int>(), "BusinessRejectReason", 380, &CLIENT::realmbases[90] } },
   { 381, { Type2Type<CLIENT::GrossTradeAmt>(), "GrossTradeAmt", 381 } },
   { 382, { Type2Type<CLIENT::NoContraBrokers>(), "NoContraBrokers", 382 } },
   { 383, { Type2Type<CLIENT::MaxMessageSize>(), "MaxMessageSize", 383 } },
   { 384, { Type2Type<CLIENT::NoMsgTypes>(), "NoMsgTypes", 384 } },
   { 385, { Type2Type<CLIENT::MsgDirection, char>(), "MsgDirection", 385, &CLIENT::realmbases[91] } },
   { 386, { Type2Type<CLIENT::NoTradingSessions>(), "NoTradingSessions", 386 } },
   { 387, { Type2Type<CLIENT::TotalVolumeTraded>(), "TotalVolumeTraded", 387 } },
   { 388, { Type2Type<CLIENT::DiscretionInst, char>(), "DiscretionInst", 388, &CLIENT::realmbases[92] } },
   { 389, { Type2Type<CLIENT::DiscretionOffset>(), "DiscretionOffset", 389 } },
   { 390, { Type2Type<CLIENT::BidID>(), "BidID", 390 } },
   { 391, { Type2Type<CLIENT::ClientBidID>(), "ClientBidID", 391 } },
   { 392, { Type2Type<CLIENT::ListName>(), "ListName", 392 } },
   { 393, { Type2Type<CLIENT::TotalNumSecurities>(), "TotalNumSecurities", 393 } },
   { 394, { Type2Type<CLIENT::BidType>(), "BidType", 394 } },
   { 395, { Type2Type<CLIENT::NumTickets>(), "NumTickets", 395 } },
   { 396, { Type2Type<CLIENT::SideValue1>(), "SideValue1", 396 } },
   { 397, { Type2Type<CLIENT::SideValue2>(), "SideValue2", 397 } },
   { 398, { Type2Type<CLIENT::NoBidDescriptors>(), "NoBidDescriptors", 398 } },
   { 399, { Type2Type<CLIENT::BidDescriptorType>(), "BidDescriptorType", 399 } },
   { 400, { Type2Type<CLIENT::BidDescriptor>(), "BidDescriptor", 400 } },
   { 401, { Type2Type<CLIENT::SideValueInd>(), "SideValueInd", 401 } },
   { 402, { Type2Type<CLIENT::LiquidityPctLow>(), "LiquidityPctLow", 402 } },
   { 403, { Type2Type<CLIENT::LiquidityPctHigh>(), "LiquidityPctHigh", 403 } },
   { 404, { Type2Type<CLIENT::LiquidityValue>(), "LiquidityValue", 404 } },
   { 405, { Type2Type<CLIENT::EFPTrackingError>(), "EFPTrackingError", 405 } },
   { 406, { Type2Type<CLIENT::FairValue>(), "FairValue", 406 } },
   { 407, { Type2Type<CLIENT::OutsideIndexPct>(), "OutsideIndexPct", 407 } },
   { 408, { Type2Type<CLIENT::ValueOfFutures>(), "ValueOfFutures", 408 } },
   { 409, { Type2Type<CLIENT::LiquidityIndType, int>(), "LiquidityIndType", 409, &CLIENT::realmbases[93] } },
   { 410, { Type2Type<CLIENT::WtAverageLiquidity>(), "WtAverageLiquidity", 410 } },
   { 411, { Type2Type<CLIENT::ExchangeForPhysical, char>(), "ExchangeForPhysical", 411, &CLIENT::realmbases[94] } },
   { 412, { Type2Type<CLIENT::OutMainCntryUIndex>(), "OutMainCntryUIndex", 412 } },
   { 413, { Type2Type<CLIENT::CrossPercent>(), "CrossPercent", 413 } },
   { 414, { Type2Type<CLIENT::ProgRptReqs, int>(), "ProgRptReqs", 414, &CLIENT::realmbases[95] } },
   { 415, { Type2Type<CLIENT::ProgPeriodInterval>(), "ProgPeriodInterval", 415 } },
   { 416, { Type2Type<CLIENT::IncTaxInd, int>(), "IncTaxInd", 416, &CLIENT::realmbases[96] } },
   { 417, { Type2Type<CLIENT::NumBidders>(), "NumBidders", 417 } },
   { 418, { Type2Type<CLIENT::TradeType, char>(), "TradeType", 418, &CLIENT::realmbases[97] } },
   { 419, { Type2Type<CLIENT::BasisPxType, char>(), "BasisPxType", 419, &CLIENT::realmbases[98] } },
   { 420, { Type2Type<CLIENT::NoBidComponents>(), "NoBidComponents", 420 } },
   { 421, { Type2Type<CLIENT::Country>(), "Country", 421 } },
   { 422, { Type2Type<CLIENT::TotNoStrikes>(), "TotNoStrikes", 422 } },
   { 423, { Type2Type<CLIENT::PriceType, int>(), "PriceType", 423, &CLIENT::realmbases[99] } },
   { 424, { Type2Type<CLIENT::DayOrderQty>(), "DayOrderQty", 424 } },
   { 425, { Type2Type<CLIENT::DayCumQty>(), "DayCumQty", 425 } },
   { 426, { Type2Type<CLIENT::DayAvgPx>(), "DayAvgPx", 426 } },
   { 427, { Type2Type<CLIENT::GTBookingInst, int>(), "GTBookingInst", 427, &CLIENT::realmbases[100] } },
   { 428, { Type2Type<CLIENT::NoStrikes>(), "NoStrikes", 428 } },
   { 429, { Type2Type<CLIENT::ListStatusType>(), "ListStatusType", 429 } },
   { 430, { Type2Type<CLIENT::NetGrossInd, int>(), "NetGrossInd", 430, &CLIENT::realmbases[101] } },
   { 431, { Type2Type<CLIENT::ListOrderStatus>(), "ListOrderStatus", 431 } },
   { 432, { Type2Type<CLIENT::ExpireDate>(), "ExpireDate", 432 } },
   { 433, { Type2Type<CLIENT::ListExecInstType, char>(), "ListExecInstType", 433, &CLIENT::realmbases[102] } },
   { 434, { Type2Type<CLIENT::CxlRejResponseTo, char>(), "CxlRejResponseTo", 434, &CLIENT::realmbases[103] } },
   { 435, { Type2Type<CLIENT::UnderlyingCouponRate>(), "UnderlyingCouponRate", 435 } },
   { 436, { Type2Type<CLIENT::UnderlyingContractMultiplier>(), "UnderlyingContractMultiplier", 436 } },
   { 437, { Type2Type<CLIENT::ContraTradeQty>(), "ContraTradeQty", 437 } },
   { 438, { Type2Type<CLIENT::ContraTradeTime>(), "ContraTradeTime", 438 } },
   { 439, { Type2Type<CLIENT::ClearingFirm>(), "ClearingFirm", 439 } },
   { 440, { Type2Type<CLIENT::ClearingAccount>(), "ClearingAccount", 440 } },
   { 441, { Type2Type<CLIENT::LiquidityNumSecurities>(), "LiquidityNumSecurities", 441 } },
   { 442, { Type2Type<CLIENT::MultiLegReportingType, char>(), "MultiLegReportingType", 442, &CLIENT::realmbases[104] } },
   { 443, { Type2Type<CLIENT::StrikeTime>(), "StrikeTime", 443 } },
   { 444, { Type2Type<CLIENT::ListStatusText>(), "ListStatusText", 444 } },
   { 445, { Type2Type<CLIENT::EncodedListStatusTextLen>(), "EncodedListStatusTextLen", 445 } },
   { 446, { Type2Type<CLIENT::EncodedListStatusText>(), "EncodedListStatusText", 446 } }
}; // 400
} // namespace CLIENT

} // namespace FIX8
